/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import org.json.JSONObject;

import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.ListSelectionEvent;
import java.awt.*;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

/**
 *
 * @author fawaa
 */
public class StudentDashboardFrame extends javax.swing.JFrame
{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName());
    DefaultListModel<Course> modelofcourses = new DefaultListModel<>();
    /**
     * Creates new form StudentDashboardFrame
     */
    Student student ;
    public StudentDashboardFrame(Student student)
    {
        this.student = student ;
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new JList<Course>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("YOUR COURSES");

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("SEARCH ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        /*
        jList2.setModel(new AbstractListModel<Course>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
         */
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jList2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jList2ComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        /*
        jList3.setModel(new AbstractListModel<Course>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
         */
        jList3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jList3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jList3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jList3ComponentShown(evt);
            }
        });
        jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList3ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel5.setText("HI");
        jLabel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel5ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(247, 247, 247)
                                                .addComponent(jLabel3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane3))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jList3AncestorAdded(AncestorEvent evt) {
    }

    private void jList3ValueChanged(ListSelectionEvent evt) {
    }



    /*
     searchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String id = idTextField.getText().trim();
                if (!id.isEmpty()) {
                    // Here you can implement your actual search logic
                    JOptionPane.showMessageDialog(null, "Searching for ID: " + id);
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter an ID!");
                }
            }
        });
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String courseTitle = jTextField1.getText().trim();

        if (courseTitle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a course ID");
            return;
        }

        ArrayList<Course> results = student.search(courseTitle);

        if (results == null || results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No course found");
            return;
        }


        DefaultListModel<String> modeloftitles = new DefaultListModel<>();

        for (int i = 0; i < results.size(); i++)
        {
            modelofcourses.addElement(results.get(i));
            modeloftitles.addElement(results.get(i).getTitle());
        }
        jList3.setModel(modeloftitles);
    }




    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
{
    // for search
}
private void jList3ComponentShown(ComponentEvent evt)
{
    // write courses according to the search

}

private void jList3MouseClicked(java.awt.event.MouseEvent evt)
{
    // open course window ?? search
    if (evt.getClickCount() == 2)
    {
        String selectedtitle = jList3.getSelectedValue();
        if (selectedtitle != null)
        {
            Course selectedcourse = null;
            for (int i = 0; i < modelofcourses.getSize(); i++)
            {
                if (selectedtitle.equals(modelofcourses.get(i).getTitle()))
                {
                    selectedcourse = modelofcourses.get(i);
                    break;
                }
            }
            new CourseWindow(selectedcourse, student).setVisible(true);
        }
    }
}
    /*
    jList2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                if (evt.getClickCount() == 2)
                {
                    Course selected = jList2.getSelectedValue();
                    if (selected != null)
                    {
                        // open new window
                         new CourseWindow (selected , student ) ;
                    }
                }
            }
        });
     */


private void jList2MouseClicked(java.awt.event.MouseEvent evt) {
    // open course window
    if (evt.getClickCount() == 2)
    {
        Course selected = jList2.getSelectedValue();
        if (selected != null)
        {
            // call the new window
        }
    }
}

    /*
    private void jList2ComponentShown(java.awt.event.ComponentEvent evt1) {
        // write student courses
        DefaultListModel<Course> model = new DefaultListModel<>();
        for ( int i = 0 ; i < student.enrolledCourses.size() ; i++ )
        {
            model.addElement(student.enrolledCourses.get(i));
        }

        JList<Course> courseList = new JList<>(model);

        java.awt.event.MouseEvent evt2 = new java.awt.event.MouseEvent() ;
        if (evt2.getClickCount() == 2)
        {
            Course selected = courseList.getSelectedValue();
            if (selected != null)
            {
                // call the new window
            }
        }
    }
    */
private void jList2ComponentShown(java.awt.event.ComponentEvent evt)
{
    DefaultListModel<Course> model = new DefaultListModel<>();

    for ( int i = 0 ; i < student.enrolledCourses.size() ; i++ )
    {
        model.addElement(student.enrolledCourses.get(i));
    }

    jList2.setModel(model);

    jList2.addMouseListener(new java.awt.event.MouseAdapter()
    {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
            if (evt.getClickCount() == 2)
            {
                Course selected = jList2.getSelectedValue();
                if (selected != null)
                {
                    // open new window
                    new CourseWindow (selected , student ) ;
                }
            }
        }
    });
}

    /*
    public void openCourseWindowWithLessons(Course course)
    {
        // JFrame setup
        JFrame frame = new JFrame(course.getTitle());
        frame.setSize(500, 500);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Main panel
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Course info panel
        JPanel infoPanel = new JPanel();
        infoPanel.setLayout(new GridLayout(0, 1, 5, 5));
        infoPanel.add(new JLabel("Course ID: " + course.getCourseId()));
        infoPanel.add(new JLabel("Title: " + course.getTitle()));
        infoPanel.add(new JLabel("Description: " + course.getDescription()));
        infoPanel.add(new JLabel("Instructor ID: " + course.getInstructorId()));

        mainPanel.add(infoPanel, BorderLayout.NORTH);

        // Lessons panel with toggle buttons
        JPanel lessonsPanel = new JPanel();
        lessonsPanel.setLayout(new GridLayout(0, 1, 5, 5));

        for (String lesson : /*course.getLessons()) {
            JToggleButton lessonButton = new JToggleButton(lesson + " (Not Watched)");
            lessonButton.addActionListener(e -> {
                if (lessonButton.isSelected()) {
                    lessonButton.setText(lesson + " (Watched)");
                } else {
                    lessonButton.setText(lesson + " (Not Watched)");
                }
            });
            lessonsPanel.add(lessonButton);
        }

        // Scroll pane for lessons if many
        JScrollPane scrollPane = new JScrollPane(lessonsPanel);
        mainPanel.add(scrollPane, BorderLayout.CENTER);

        frame.add(mainPanel);
        frame.setVisible(true);
    }
    */


private void jLabel5ComponentShown(java.awt.event.ComponentEvent evt)
{
    // write student name + "HI"
    jLabel5.setText("HI" + " " + student.getUsername().toUpperCase());
}

/**
 * @param args the command line arguments
 */




// Variables declaration - do not modify
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private JList<Course> jList2;
private JList<String> jList3;
private javax.swing.JScrollPane jScrollPane2;
private javax.swing.JScrollPane jScrollPane3;
private javax.swing.JTextField jTextField1;
// End of variables declaration
}
